# -----------------------------------------------------------------
# Filename: install_microsoft_defender.yaml
# Written : 14-November-2024 (Raymond Val)
# Purpose : 
# Notes   :
#         
#   Revision History:
#   Name:           Date:        Description:
# -----------------------------------------------------------------

---
- name: Install Microsoft Defender for Linux
  hosts: all
  gather_facts: true
  become: true

  vars:
    edr_distro: rhel  # ansible_distribution
    edr_version: 8    # ansible_distribution_major_version
    edr_channel: insiders-fast # insiders-fast, insiders-slow, prod

  tasks:

    # Ensure All software requirements are met
    - name: Ensure required files are installed
      yum:
        name:
          - audit
          - glibc
          - policycoreutils
          - libsemanage
          - selinux-policy-targeted
          - libmnl
          - libnfnetlink
          - libnetfilter_queue
          - glib2
        state: present
    
    # Install Microsoft Defender Onboarding package      
    # task: onboarding_setup.yml
    - name: Create MDATP directories
      file:
        path: /etc/opt/microsoft/mdatp/
        recurse: true
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Register mdatp_onboard.json
      stat:
        path: /etc/opt/microsoft/mdatp/mdatp_onboard.json
      register: mdatp_onboard

    - name: Extract WindowsDefenderATPOnboardingPackage.zip into /etc/opt/microsoft/mdatp
      unarchive:
        src: files/WindowsDefenderATPOnboardingPackage.zip
        dest: /etc/opt/microsoft/mdatp
        mode: 0600
        owner: root
        group: root
      when: not mdatp_onboard.stat.exists

    # Install Repository
    # task: add_apt_repo.yml
    - name: Add Microsoft APT key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Microsoft apt repository for MDATP
      apt_repository:
        repo: deb [arch=arm64,armhf,amd64] https://packages.microsoft.com/{{ edr_distro }}/{{ edr_version }}/prod [codename] main
        update_cache: yes
        state: present
        filename: microsoft-[channel]
      when: ansible_os_family == "Debian"

    - name: Add Microsoft DNF/YUM key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
      when: ansible_os_family == "RedHat"

    - name: Add  Microsoft yum repository for MDATP
      yum_repository:
        name: packages-microsoft-insiders-fast
        description: Microsoft Defender for Endpoint Insiders Fast packages
        file: microsoft-defender
        baseurl: https://packages.microsoft.com/{{ edr_distro }}/{{ edr_version }}/insiders-fast/ 
        gpgcheck: yes
        enabled: Yes
      when: ansible_os_family == "RedHat"

    - name: Add  Microsoft yum repository for MDATP
      yum_repository:
        name: packages-microsoft-insiders-slow
        description: Microsoft Defender for Endpoint Insiders Slow packages
        file: microsoft-defender
        baseurl: https://packages.microsoft.com/{{ edr_distro }}/{{ edr_version }}/insiders-slow/ 
        gpgcheck: yes
        enabled: No
      when: ansible_os_family == "RedHat"

    - name: Add  Microsoft yum repository for MDATP
      yum_repository:
        name: packages-microsoft-prod
        description: Microsoft Defender for Endpoint Product packages
        file: microsoft-defender
        baseurl: https://packages.microsoft.com/{{ edr_distro }}/{{ edr_version }}/prod/ 
        gpgcheck: yes
        enabled: No
      when: ansible_os_family == "RedHat"            
          
    # install_mdatp.yml
    - name: include onboarding tasks
      import_tasks:
        file: ../roles/onboarding_setup.yml
    - name: add apt repository
      import_tasks:
        file: ../roles/add_apt_repo.yml
    - name: Install MDATP
      apt:
        name: mdatp
        state: latest
        update_cache: yes

    # uninstall_mdatp.yml
    - name: Uninstall MDATP
      apt:
        name: mdatp
        state: absent

    # install_mdatp_dnf.yml
    - name: include onboarding tasks
      import_tasks:
        file: ../roles/onboarding_setup.yml
    - name: add apt repository
      import_tasks:
        file: ../roles/add_yum_repo.yml
    - name: Install MDATP
      dnf:
        name: mdatp
        state: latest
        enablerepo: packages-microsoft-[channel]

    # uninstall_mdatp_dnf.yml
    - name: Uninstall MDATP
      dnf:
        name: mdatp
        state: absent