# -----------------------------------------------------------------
# Filename: install_mdatp.yml
# Written : 15-November-2024 (Raymond Val)
# Purpose : Install Microsoft Defender
# Notes   :
#
#   Revision History:
#   Name:           Date:        Description:
# -----------------------------------------------------------------

---
- name: Include onboarding tasks
  ansible.builtin.import_tasks:
    file: tasks/onboarding_setup.yml

- name: Add apt repository
  ansible.builtin.import_tasks:
    file: tasks/add_apt_repo.yml

- name: Install MDATP
  ansible.builtin.package:
    name: mdatp
    state: present
    update_cache: true
